Updated usage message and such

diff --git a/start_notebook b/start_notebook
--- a/start_notebook
+++ b/start_notebook
@@ -2,7 +2,31 @@
 # Authors: James McDougall [Github JamesMcDougallJr], Scott Sakai
 # The goal of this script is to start a jupyter notebook on comet by using the Reverse Proxy service.
 # This makes a secure connection between the user's local machine and the RP server.
+## =====================================================================================
+## Usage
+##  ./start_notebook [-p <string>] [-d <string>] [-b <string>] [-t <number>]
+##
+##      -p: The partition your job will be started on. This can be either compute or
+##          debug. Reminder that the debug queue has a max time of 30 minutes.
+##
+##      -d: The top level directory for your jupyter notebook. 
+##          Default: /home/$USER 
+##
+##      -A: The Allocation (project) your notebook will be "charged" to. 
+##          Default: the same as your system default. This is different for every user, 
+##          but you can see your accounts using the `show_accounts` command.
+##
+##      -b: The batch script you want to submit. Of course the batch script needs to
+##          start a jupyter notebook otherwise this script will fail.
+##          Default: ./batch/batch_notebook.sh
+##
+##      -t: The time in MINTUES that you want the jupyter notebook to run for.
+##          Default: 30 minutes
+##
+##
+## =====================================================================================
 
+DEBUG=0
 start_dir=""
 runtime="00:30:00"
 project=""
@@ -11,6 +35,7 @@ batch_script=""
 
 # Entry point for starting a notebook. Handles slurm processes and retrives url from slurm output
 function start_notebook () {
+
     # get the Reverse proxy API_TOKEN
     api_token_response=$(curl -s https://manage.comet-user-content.sdsc.edu/getlink.cgi)
     api_token=${api_token_response#*"Your token is "} #strip the token out of response
@@ -49,8 +74,8 @@ function start_notebook () {
     echo -e "\t$jupyter_url"
 
     # start the batch script with the api token and the starting directory
-    # Argument 1 is the RP api token
-    # Argument 2 is the tmpfile path
+    # Argument 1 to the batch script is the RP api token
+    # Argument 2 to the batch script is the tmpfile path
 
     if [ "$partition" = "" ]; then
         echo "Using default partition: compute"
@@ -63,27 +88,31 @@ function start_notebook () {
 
     if [ "$batch_script" = "" ]; then
         echo "No batch script specified. Using ./batch/batch_notebook.sh"
-        batch_script="batch/batch_notebook.sh"
+        batch_script="./batch/batch_notebook.sh"
     fi
 
     if [ "$project" = "" ]; then
-        echo "Using default project"
-        echo "Batch Script: $batch_script"
-        echo "Project: $project"
-        echo "Partition: $partition"
-        echo "Tempfile: $tmpfile"
-        echo "Api token: $api_token"
-        echo "Jupyter token: $jupyter_token"
-        echo "runtime: $runtime"
+        if [[ $DEBUG -eq 1 ]]; then
+            echo "Using default project"
+            echo "Batch Script: $batch_script"
+            echo "Project: $project"
+            echo "Partition: $partition"
+            echo "Tempfile: $tmpfile"
+            echo "Api token: $api_token"
+            echo "Jupyter token: $jupyter_token"
+            echo "runtime: $runtime"
+        fi
         sbatch -t $runtime -p $partition $batch_script $api_token $tmpfile
     else
-        echo "Project: $project"
-        echo "Partition: $partition"
-        echo "Batch script: $batch_script"
-        echo "Tempfile: $tmpfile"
-        echo "Api token: $api_token"
-        echo "Jupyter token $jupyter_token"
-        echo "Runtime: $runtime"
+        if [[ $DEBUG -eq 1 ]]; then
+            echo "Project: $project"
+            echo "Partition: $partition"
+            echo "Batch script: $batch_script"
+            echo "Tempfile: $tmpfile"
+            echo "Api token: $api_token"
+            echo "Jupyter token $jupyter_token"
+            echo "Runtime: $runtime"
+        fi
         sbatch -t $runtime -A $project -p $partition $batch_script $api_token $tmpfile
     fi
 }
@@ -138,6 +167,8 @@ usage() {
     echo Default Time is 30 mins
 }
 
+input_runtime=""
+
 OPTIND=1
 while getopts "h?:d:A:p:b:t:" opt; do
     case "$opt" in
@@ -149,12 +180,21 @@ while getopts "h?:d:A:p:b:t:" opt; do
         A)  project=$OPTARG   ;;
         p)  partition=$OPTARG ;;
         b)  batch_script=$OPTARG ;;
-        t)  runtime=$(parse_time $OPTARG) ;;
+        t)  input_runtime=$OPTARG
+            runtime=$(parse_time $OPTARG) 
+            ;;
         *)  echo "Error: invalid optional argument $OPTARG" 
             usage 
             exit 1
             ;;
     esac
 done
+
+if [ $partition = "debug" ]; then
+    if [ $input_runtime -gt 30 ]; then
+        echo "Invalid runtime for debug queue. Must be less than or equal to 30 minutes"
+        exit 1
+    fi
+fi
 
 start_notebook $start_dir $runtime $project
