Updated start notebook to catch a few errors

diff --git a/start_notebook b/start_notebook
--- a/start_notebook
+++ b/start_notebook
@@ -52,10 +52,22 @@ function start_notebook () {
         exit 1
     fi
         
-    JUP_CONFIG_DIR="$(jupyter --config-dir)/rps"
-    mkdir -p $JUP_CONFIG_DIR
-    chmod 0700 $JUP_CONFIG_DIR
-    export config=`mktemp -p $JUP_CONFIG_DIR tmp.XXXXXX.py` || (echo "Failed to make the jupyter_secure directory" && exit 1)
+
+    if jupyter --config-dir; then
+        JUP_CONFIG_DIR="$(jupyter --config-dir)/rps"
+    else 
+        echo "Jupyter command failed. Exit Peacefully."
+        exit 1
+    fi
+
+    mkdir -p $JUP_CONFIG_DIR || (echo "Failed to create directory $JUP_CONFIG_DIR" && exit 1)
+    chmod 0700 $JUP_CONFIG_DIR || (echo "Failed to change permissions on directory $JUP_CONFIG_DIR" && exit 1)
+    export config=`mktemp -p $JUP_CONFIG_DIR tmp.XXXXXX.py` 
+
+    if [[ $config = "" ]]; then
+        echo "Failed to make tempfile in $JUP_CONFIG_DIR"
+        exit 1
+    fi
 
     # Make a random ssl token
     jupyter_token=$(openssl rand -hex 16)
@@ -69,6 +81,7 @@ function start_notebook () {
     else
         echo "c.NotebookApp.notebook_dir = '$start_dir'" | cat >> "$config"
     fi
+
     echo "c.NotebookApp.allow_origin = '*'" | cat >> "$config"
     echo "c.NotebookApp.allow_remote_access = True" | cat >> "$config"
 
