Update start-jupyter to prevent conflict between -s and -b flags

diff --git a/start-jupyter b/start-jupyter
--- a/start-jupyter
+++ b/start-jupyter
@@ -173,47 +173,56 @@ usage() {
     echo "-s: Choose between 'notebook' and 'jupyterlab'"
 }
 
-while getopts "h?:d:A:s:p:b:t:i" opt; do
-    case "$opt" in
-        h|\?)
-            usage 
-            exit 0
-            ;;
-        s)  server=$OPTARG
-            ;;
-        d)  start_dir=$OPTARG 
-            ;;
-        A)  project=$OPTARG   
-            ;;
-        p)  partition=$OPTARG 
-            ;;
-        b)  script=$OPTARG 
-            ;;
-        i)  INFO=1 
-            ;;
-        t)  input_runtime=$OPTARG 
-            runtime=$(parse_time $OPTARG) 
-            ;;
-        *)  echo "Error: invalid optional argument $OPTARG" 
-            usage 
-            exit 1
-            ;;
-    esac
+err=0
+sb_conflict=0
+while [ $OPTIND -le "$#" ]
+do
+    if getopts "h?:d:A:s:p:b:t:i" opt; then
+        case "$opt" in
+            h|\?)
+                usage 
+                exit 0
+                ;;
+            s)  server=$OPTARG
+                sb_conflict=$((sb_conflict+1))
+                ;;
+            d)  start_dir=$OPTARG 
+                ;;
+            A)  project=$OPTARG   
+                ;;
+            p)  partition=$OPTARG 
+                ;;
+            b)  script=$OPTARG 
+                sb_conflict=$((sb_conflict+1))
+                ;;
+            i)  INFO=1 
+                ;;
+            t)  input_runtime=$OPTARG 
+                runtime=$(parse_time $OPTARG) 
+                ;;
+            *)  echo "Error: invalid optional argument $OPTARG" 
+                err=1
+                ;;
+        esac
+    else
+            pos_args=1
+            err=1
+            ((OPTIND++))
+    fi
 done
 
-remaining=${@:$OPTIND}
-if [[ ${#remaining[@]} > 1 ]]; then
-    echo "Invalid Arguments Remaining: $remaining"
-    echo "There should be no positional arguments here."
-    usage
-    exit 1
-fi
+[[ $pos_args ]] && echo "Encountered positional arguments where none are required."
+
+# if there is a conflict between the -s and -b flags
+[[ $sb_conflict = 2 ]] && echo "You cannot use the -s flag and the -b flag simultaneously" 
 
 if [[ $partition = "debug" ]]; then
     if [[ $input_runtime -gt 30 ]]; then
         echo "Invalid runtime for debug queue. Must be less than or equal to 30 minutes"
-        exit 1
+        err=1
     fi
 fi
+
+[[ $err = 1 ]] && usage && exit 1
 
 start-jupyter
