updating start_* scripts

diff --git a/start_notebook b/start_notebook
--- a/start_notebook
+++ b/start_notebook
@@ -59,20 +59,21 @@ function start_notebook () {
 
     # remove extra spaces before or after
     if jupyter --config-dir; then
-        jup_conf_dir="$(jupyter --config-dir)/rps"
+        jup_conf_rps_dir="$(jupyter --config-dir)/rps"
     else 
         echo "It looks like you don't have jupyter installed on your account."
         echo "To learn how to install Jupyter using Miniconda, check out this link: https://comet-notebooks-101.readthedocs.io/en/comet/prerequisites.html"
         exit 0
     fi
+    echo "debug:  jup_conf_rps_dir= $jup_conf_rps_dir"
 
     # ensure the jupyter config directory exists and is accessible.
     # make a temp file there for the rps to read tokens
-    mkdir -p $jup_conf_dir || (echo "Failed to create directory $jup_conf_dir" && exit 1)
-    chmod 0700 $jup_conf_dir || (echo "Failed to change permissions on directory $jup_conf_dir" && exit 1)
-    export config=`mktemp -p $jup_conf_dir tmp.XXXXXX.py` 
+    mkdir -p $jup_conf_rps_dir || (echo "Failed to create directory $jup_conf_rps_dir" && exit 1)
+    chmod 0700 $jup_conf_rps_dir || (echo "Failed to change permissions on directory $jup_conf_rps_dir" && exit 1)
+    export config=`mktemp -p $jup_conf_rps_dir tmp.XXXXXX.py` 
 
-    [[ $config = "" ]] && echo "Failed to make tempfile in $jup_conf_dir" && exit 1
+    [[ $config = "" ]] && echo "Failed to make tempfile in $jup_conf_rps_dir" && exit 1
 
     # Make a random ssl token
     jupyter_token=$(openssl rand -hex 16)
