Update start_notebook

diff --git a/start_notebook b/start_notebook
--- a/start_notebook
+++ b/start_notebook
@@ -97,7 +97,7 @@ function start_notebook () {
     [[ $project = "" ]] || project="-A $project"
 
     check_available sbatch "" && sys="slurm"
-    check_available torque "" && sys="torque" 
+    check_available qsub "" && sys="torque" 
 
     [[ $script = "" ]] && echo "Using ./$sys/notebook.sh" && script="./$sys/notebook.sh"
 
@@ -119,14 +119,23 @@ function start_notebook () {
     if [[ $sys = "slurm" ]]; then
         sbr=$(sbatch $runtime $project -p $partition $script)
         if [[ "$sbr" =~ Submitted\ batch\ job\ ([0-9]+) ]]; then
-            cleanup "${BASH_REMATCH[1]}" $config &
+            cleanup_slurm "${BASH_REMATCH[1]}" $config &
             exit 0
         else
-            echo "sbatch failed"
+            echo "Sbatch failed"
             exit 1
         fi
     elif [[ $sys = "torque" ]]; then
-        qsub -l walltime=${runtime#-t **} $project $script
+        qout=$(qsub -l walltime=${runtime#-t **} $project $script)
+	echo $qout
+	if [[ "$qout" =~ [0-9]+.tscc-mgr[0-9].local ]]; then
+	    qid=$(echo "${BASH_REMATCH[@]}" | sed 's/[^0-9]*//g')
+	    #cleanup_torque $qid $config &
+	    exit 0
+	else
+	    echo "Torque failed"
+	    exit 1
+	fi
     else
         echo "No queue system was found. Please use slurm or torque"
     fi
